### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by harman-f** [harman-f/MHI2_MIB2_AIO_FW_Update_Template#1]
- [x] Auto detect G11 FW and start conversion
- [x] add skin change on VW: some issues with stuck on boot screen on older FW/car model - Skin1
- [x] Add to LOG: `ls` of RCC/MMX/APP root
- [x] Create Conversion LOG
